In [18]:
import itertools
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import NullFormatter
import pandas as pd
import numpy as np
import math
import matplotlib.ticker as ticker
from sklearn import preprocessing
%matplotlib inline

In [147]:
df = pd.read_csv('https://raw.githubusercontent.com/achmatim/data-mining/main/Dataset/iris.csv')
df[50:70]

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm            Label
50            7.0           3.2            4.7           1.4  Iris-versicolor
51            6.4           3.2            4.5           1.5  Iris-versicolor
52            6.9           3.1            4.9           1.5  Iris-versicolor
53            5.5           2.3            4.0           1.3  Iris-versicolor
54            6.5           2.8            4.6           1.5  Iris-versicolor
55            5.7           2.8            4.5           1.3  Iris-versicolor
56            6.3           3.3            4.7           1.6  Iris-versicolor
57            4.9           2.4            3.3           1.0  Iris-versicolor
58            6.6           2.9            4.6           1.3  Iris-versicolor
59            5.2           2.7            3.9           1.4  Iris-versicolor
60            5.0           2.0            3.5           1.0  Iris-versicolor
61            5.9           3.0            4.2           1.5  Iris-versicolor
62            6.0           2.2            4.0           1.0  Iris-versicolor
63            6.1           2.9            4.7           1.4  Iris-versicolor
64            5.6           2.9            3.6           1.3  Iris-versicolor
65            6.7           3.1            4.4           1.4  Iris-versicolor
66            5.6           3.0            4.5           1.5  Iris-versicolor
67            5.8           2.7            4.1           1.0  Iris-versicolor
68            6.2           2.2            4.5           1.5  Iris-versicolor
69            5.6           2.5            3.9           1.1  Iris-versicolor

In [3]:
#Convert To numpy array, for independent variables
X = df[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']].values  #.astype(float)
X[0:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [6]:
y = df[['Label']].values  #.astype(float)
y[0:5]

array([['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa']], dtype=object)

In [8]:
#Data Normalization
#Adjust data scale
X = preprocessing.StandardScaler().fit(X).transform(X.astype(float))
X[0:5]

array([[-0.90068117,  1.03205722, -1.3412724 , -1.31297673],
       [-1.14301691, -0.1249576 , -1.3412724 , -1.31297673],
       [-1.38535265,  0.33784833, -1.39813811, -1.31297673],
       [-1.50652052,  0.10644536, -1.2844067 , -1.31297673],
       [-1.02184904,  1.26346019, -1.3412724 , -1.31297673]])

In [109]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=3)#20% data test 80% data train
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (120, 4) (120, 1)
Test set: (30, 4) (30, 1)


In [110]:
from sklearn.neighbors import KNeighborsClassifier

In [114]:
print("Best K value : ", math.ceil(math.sqrt(150/2)))

Best K value :  9


In [111]:
k = 9 #Train model and predict 
knn = KNeighborsClassifier(n_neighbors = k).fit(X_train,y_train)
knn

C:\Users\asus\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=9)

In [112]:
#Predicting with data test
y_pred = knn.predict(X_test)
y_pred[0:5]

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa'], dtype=object)

In [113]:
from sklearn import metrics
print("Train set Accuracy: ", metrics.accuracy_score(y_train, knn.predict(X_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test, y_pred))

Train set Accuracy:  0.95
Test set Accuracy:  0.9666666666666667


### Without normalization, because the data scale is not too far

In [119]:
A = df[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']].values  #.astype(float)
A[0:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [121]:
B = df[['Label']].values
B[0:5]

array([['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa']], dtype=object)

In [133]:
X_train, X_test, y_train, y_test = train_test_split( A, B, test_size=0.2, random_state=3)#20% data test 80% data train
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (120, 4) (120, 1)
Test set: (30, 4) (30, 1)


In [134]:
k = 9 #Train model and predict 
knn = KNeighborsClassifier(n_neighbors = k).fit(X_train,y_train)
knn

C:\Users\asus\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=9)

In [135]:
y_pred = knn.predict(X_test)
y_pred[0:5]

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa'], dtype=object)

In [136]:
print("Train set Accuracy: ", metrics.accuracy_score(y_train, knn.predict(X_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test, y_pred))

Train set Accuracy:  0.9666666666666667
Test set Accuracy:  1.0


In [150]:
SL = input("Input Sepal Length : ")
SW = input("Input Sepal Width  : ")
PL = input("Input Petal Length : ")
PW = input("Input Petal Width  : ")
P = np.array([SL,SW,PL,PW])
X_test[0] = P
y_pred = knn.predict(X_test)
y_pred[0]

Input Sepal Length : 10
Input Sepal Width  : 1
Input Petal Length : 3.5
Input Petal Width  : 3


'Iris-versicolor'